# Generated by Django 4.0.6 on 2022-08-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_lives_in_account_profile_pic'),
        ('chat', '0003_chat_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat', to='chat.chat')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_message', to='user.account')),
            ],
        ),
    ]
