# Generated by Django 4.0.6 on 2022-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sentAt',
            field=models.DateTimeField(null=True),
        ),
    ]
