# Generated by Django 4.0.6 on 2022-08-06 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_lives_in_account_profile_pic'),
        ('chat', '0005_message_sentat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='user.account'),
        ),
    ]
