# Generated by Django 4.0.6 on 2022-08-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_lives_in_account_profile_pic'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='members',
        ),
        migrations.AddField(
            model_name='node',
            name='members',
            field=models.ManyToManyField(to='user.account'),
        ),
    ]
