# Generated by Django 4.0.6 on 2022-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lives_in',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='media/profile/'),
        ),
    ]
